sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1412
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tS2ekWSgRDXmiSserU7
    access-key-secret: mdpgQWAnQarPa08WsCXfq4EoUtOwtT
    bucket-name: guduyili