sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1412
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tDUk8vCMri5oxWMfz6o
    access-key-secret: GdP0pulxgPp9sezKcnvVO2CqTCxP7a
    bucket-name: guduyili
  redis:
    host: localhost
    port: 6379
    password: 1412
    database: 10
  wechat:
    appid: wx233f5ca2dbb90391
    secret: 08c9af74194af7d25362c5ade2e6f062

