sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1412
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t9n57wA2HMTpFs69mbx
    access-key-secret: 5AhUIi4HqVNvRfsdxY2xfCmUztMqyG
    bucket-name: guduyili